global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8081']

