name: Deploy Product Service

on:
  push:
    paths:
      - 'service/product-service/**'
      - '.github/workflows/deploy.yml'
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build product-service image
        run: |
          docker build -t ecommerce-platform-product-service:latest ./service/product-service
          docker tag ecommerce-platform-product-service:latest frey547/ecommerce-platform-product-service:latest

      - name: Push image to Docker Hub
        run: |
          docker push frey547/ecommerce-platform-product-service:latest

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 2222
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/projects/ecommerce-platform
            #docker pull frey547/ecommerce-platform-product-service:latest
            #docker-compose up -d --no-build product-service

